### ISSUE TITLE
generating executable

### ISSUE THREAD

**Issue by bensetup125** [ClubeDosGeeksCoding/electron-angularjs-sqlite#1]
Hello JAYR,

Thanks for your great work. 

I've used your library recently and it works well in dev mode.
But when I generate an executable for max OS X, there is a problem with db connection. It couldn't read data from db.

Please help me how to create an executable that works with db.

Regards
Ben

**Comment by jayralencar** [comment]
Hi @Creative125,

In the same folder of the executable, create a folder called model, and put the file database.db inside it.

**Comment by bensetup125** [comment]
Hello @jayralencar 

I already tried it, but no lucky
![screen shot 2016-09-20 at 6 28 21 am](https://cloud.githubusercontent.com/assets/22220484/18668517/7f63679e-7efb-11e6-996a-3a86d0efe542.png)

**Comment by bensetup125** [comment]
If you want to check source code, I can provide

**Comment by jayralencar** [comment]
Start the APP and open the DevTools (Ctrl+shift+i) and show me the error.

**Comment by bensetup125** [comment]
I can open the DevTools when run by 'npm start', but can't open it in executable file

and when I run app by 'npm start', it works without error

**Comment by jayralencar** [comment]
Remove the // of this line: https://github.com/ClubeDosGeeksCoding/electron-angularjs-sqlite/blob/master/main.js#L23

E pack again.

**Comment by bensetup125** [comment]
ok. let me try

**Comment by bensetup125** [comment]
it says SQL error or missing database
I put model folder in executable folder

**Comment by bensetup125** [comment]
Hello @jayralencar 
do you have any clue?

**Comment by jayralencar** [comment]
Make sure that your app is not in a folder that needs administrator permissions

**Comment by bensetup125** [comment]
yes, they are in my work folder which doesn't need admin permissions

**Comment by jayralencar** [comment]
Send me a print of the error!

**Comment by bensetup125** [comment]
![screen shot 2016-09-21 at 9 03 29 am](https://cloud.githubusercontent.com/assets/22220484/18714099/4e10e39e-7fda-11e6-94b7-18bb887a95d7.png)

**Comment by bensetup125** [comment]
Here is the comment
you can find full source code here
https://github.com/Creative125/angular-excel-sqlite

**Comment by jayralencar** [comment]
Hey man, the file database.db is outside of model/
https://github.com/Creative125/angular-excel-sqlite/blob/master/services/dbService.js#L4

Move it to same folder of the executable file or edit this line to:

```
var db = sqlite.connect('model/database.db');
```

**Comment by bensetup125** [comment]
yes, I already edit this line
var db = sqlite.connect('database.db');

**Comment by bensetup125** [comment]
![screen shot 2016-09-21 at 9 25 57 am](https://cloud.githubusercontent.com/assets/22220484/18715052/736b4a14-7fdd-11e6-8bff-e61d651a611a.png)

**Comment by bensetup125** [comment]
and database.db is in same folder with myApp

**Comment by bensetup125** [comment]
could you please try to run my source code?

**Comment by jayralencar** [comment]
I ran your code. I packed and I did put database.db in same folder of executable file. It works.

**Comment by bensetup125** [comment]
um... 
'npm run osx' is the command to pack, right?

**Comment by bensetup125** [comment]
could you please upload your executable folder?

**Comment by jayralencar** [comment]
I am using windows

**Comment by bensetup125** [comment]
um... I am on Mac

**Comment by bensetup125** [comment]
so you can't help me to fix mac issue?

**Comment by jayralencar** [comment]
I don't think so.

**Comment by bensetup125** [comment]
absolute filepath resolved my issue on mac
var db = sqlite.connect(__dirname + '/database.db');
